_commit: 1.1.1
_src_path: https://github.com/tpluscode/github-copier-template.git
auto_tag: true
changesets: true
main_branch: master
node_version: 16
package_manager: yarn
release_with_changesets: false

